### ISSUE TITLE
Bump vscodium to 1.50.1

### ISSUE THREAD

**Issue by ghost** [piedar/overboard#1]
Hi, I'm excited that there's an up-to-date vscodium overlay available.
However, just recently version 1.50.1 was released, and I was hoping you could bump the existing ebuild to the new release?

**Comment by piedar** [comment]
Alas, my development machine has gone down.  I must repair it before I can update any ebuilds.

**Comment by ghost** [comment]
@piedar No problem, I'm using a different overlay with the regular `vscode-oss `and the `strip_urls `use flag which (similarly to vscodium) strips out the telemetry urls. Thank you anyway!
